FROM nvidia/cuda:12.6.1-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3.12 python3-pip && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir transformers torch fastapi uvicorn

COPY gemma_server.py .

EXPOSE 8010

CMD ["python3", "gemma_server.py"]
